# Generated by Django 4.2.1 on 2023-06-30 06:55

from django.db import migrations, models
import django.db.models.deletion
import shop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to=shop_app.models.category_image_directory_path)),
                ('alt', models.CharField(blank=True, default='Description image no yet', max_length=255)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop_app.category')),
            ],
        ),
    ]
