# Generated by Django 4.2.1 on 2023-06-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_imagecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price_p', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('count_p', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('free_delivery', models.BooleanField(default=False)),
                ('rating', models.FloatField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('quantity_sold', models.SmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_app.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
