# Generated by Django 4.2.1 on 2023-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(related_name='specifications', to='shop_app.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
