# Generated by Django 4.2.1 on 2023-06-10 17:12

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[auth_app.models.validate_number]),
        ),
    ]
